### PR TITLE
Block duplicate upload

### PR DESCRIPTION
**Pull request by norjen**
Another pull request - hope this is acceptable?

This change will check if an existing package with an identical version number is present, if true the package will not be uploaded to Intune. When implemented New-AppPackage and New-UpdatePackage can be scheduled daily and will only upload a package to Intune if it's newer than the previous or no previous package exists.

### CODE REVIEW

**Comment by aaronparker** [comment]
The solution is currently writing a Notes property to the application with the intention of using this is the unique identifier for the package, e.g.:

```json
{"CreatedBy":"PSPackageFactory","Guid":"a0042672-7240-4312-892e-39623320c0a3","Date":"2022-12-12"}
```

Checking for duplicate applications in Intune should check this value rather than the display name. I'm open to suggestions for improving this property when checking for duplicates.

**Comment by norjen** [comment]
Thanks for your feedback, and I understand your perspective.

First let's talk about the concept - As I understand the concept, a given piece of software (eg Mozilla Firefox) can have one or two packages, either in "packages/app" or "packages/update" or both.

•	The purpose of "packages/app" is to install the software on a machine where it’s currently not installed.
•	The purpose of "packages/update" is to update software on a machine where it’s currently installed, independently of how the software was originally installed (manually, intune, etc.)

If the above is correct, then I see the packages as separate entities, eg having a separate lifecycle, and thus having a different “PSPackageFactoryGuid” (which they don’t have today). As I see it, when this is separate guids. we can use the “PSPackageFactoryGuid” to identify which package needs an updated version.

I would propose to implement a check for duplicate GUIDs in “update-packagejson.yml” to ensure a unique PSPackageFactoryGuid in all app.json.

If I’m in line with your thoughts, I will update the Pull Request to identify packages on PSPackageFactoryGuid and make a check for duplicate GUIDs in “update-packagejson.yml”

**Comment by aaronparker** [comment]
The Notes field should be used to identify the same package via the GUID, and then the Version property can be used to determine whether a new version of the application needs to be imported.

And you're correct, I need to implement a check of the App.json in the packages to ensure there are no duplicate GUIDs.

**Comment by norjen** [comment]
I update the pull request as requested ;-)

**Pull request merged**
