### PR TITLE
Fix to convert AllowAvailableUninstall of Add-IntuneWin32App parameter

### LINKED ISSUE #53: Cannot process argument transformation on parameter 'AllowAvailableUninstall'
After pull request #51 i'm getting the following error on the packages of chrome and firefox. 
`
Add-IntuneWin32App : Cannot process argument transformation on parameter 'AllowAvailableUninstall'. Cannot convert value "System.String" to type "System.Management.Automation.SwitchParameter". Boolean para
meters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At C:\IntuneProjects\packagefactory\scripts\Create-Win32App.ps1:496 char:40
    +         $Win32App = Add-IntuneWin32App @Win32AppArgs
    +                                        ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-IntuneWin32App], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Add-IntuneWin32App
`
If i comment out the part in Create-Win32App.ps1 it is working again.

### PR DESCRIPTION
**Pull request by kenchan0130**
Fix #53

### CODE REVIEW

**Comment by aaronparker** [comment]
A better fix might be to update the `AllowAvailableUninstall ` value in the `App.json` to a boolean:

```json
  "Program": {
    "InstallTemplate": "Deploy-Application.exe -DeploymentType \"Install\" -DeployMode \"Silent\"",
    "InstallCommand": "Deploy-Application.exe -DeploymentType \"Install\" -DeployMode \"Silent\"",
    "UninstallCommand": "Deploy-Application.exe -DeploymentType \"Uninstall\" -DeployMode \"Silent\"",
    "InstallExperience": "system",
    "DeviceRestartBehavior": "suppress",
    "AllowAvailableUninstall": "false"
  },
```

to:

```json
  "Program": {
    "InstallTemplate": "Deploy-Application.exe -DeploymentType \"Install\" -DeployMode \"Silent\"",
    "InstallCommand": "Deploy-Application.exe -DeploymentType \"Install\" -DeployMode \"Silent\"",
    "UninstallCommand": "Deploy-Application.exe -DeploymentType \"Uninstall\" -DeployMode \"Silent\"",
    "InstallExperience": "system",
    "DeviceRestartBehavior": "suppress",
    "AllowAvailableUninstall": false
  },
```

**Comment by kenchan0130** [comment]
@aaronparker 
I agree there’s no need to handle boolean values as strings.
Since the `DetectionRule.Check32BitOn64System` of `App.json` adopted string for bool values, I have adapted the current configuration file format.

If it is acceptable to use the bool type in the configuration file, I will change it that way.

**Comment by kenchan0130** [comment]
@aaronparker 
I have taken additional measures for this issue. Please review.

**Comment by kenchan0130** [comment]
@aaronparker 
This is just a friendly reminder that I am waiting for your review.

**Pull request merged**
